### ISSUE TITLE
Error on QGIS 3.16

### ISSUE THREAD

**Issue by ditafaith** [stangandaho/Extractor#5]
Hi @stangandaho 
I am working on QGIS 3.16.11 version, then when I try to open plugin extractor, got the following message. Any suggestion to solve this issue?

> 2023-12-14T19:47:43     WARNING    Traceback (most recent call last):
>               File "/home/saka/.local/share/QGIS/QGIS3/profiles/default/python/plugins/extractor/Extractor.py", line 193, in run
>               self.dlg.show()
>              AttributeError: 'Extractor' object has no attribute 'dlg'

**Comment by stangandaho** [comment]
Hi
I rebuild the plugin according to the issue you're experiencing.
Download the zip file here
<https://drive.google.com/file/d/160PHbvOQMyhkIp-_sCZuf7VaTWeeWnFa/view?usp=drive_link>
and reinstall the plugin from 'Install from ZIP' option in QGIS. Let me
know if the problem is fixed.

**Comment by ditafaith** [comment]
Thanks for your response @stangandaho 
After I upgraded the QGIS version 3.26 and install the new package from your link, the error still appear,

```
2023-12-14T21:26:05     WARNING    Traceback (most recent call last):
              File "/home/saka/.local/share/QGIS/QGIS3/profiles/default/python/plugins/extractor/Extractor.py", line 190, in run
              self.dlg = ExtractorDialog()
              File "/home/saka/.local/share/QGIS/QGIS3/profiles/default/python/plugins/extractor/Extractor_dialog.py", line 60, in __init__
              self.setupUi(self)
              File "", line 279, in setupUi
              File "", line 293, in retranslateUi
             AttributeError: 'QComboBox' object has no attribute 'setPlaceholderText'
```

**Comment by stangandaho** [comment]
If you upgraded to QGIS 3.26, try to install the plugin from standard
plugin repository.
If the issue persists, go to *Help > About >> Python version* and tell me
the python version you're using. Normally it must be 3.7.9 +

**Comment by ditafaith** [comment]
I removed and re-install from normal way. When I open the plugin, it showed an error.
I checked the Python version of QGIS in my Ubuntu machine is 3.8.10.
However, I installed the plugin on Windows machine, it is working well. There is probably an issue in my QGIS installation. Thanks for your response.

**Comment by stangandaho** [comment]
Thank you for bringing this to my attention. It seems there might be an issue specific to the pyqt5 version in your QGIS installation on Ubuntu. Try:

```
sudo apt-get install python3-pip
sudo python3 -m pip install pyqt5
````

The plugin is confirmed to be working on Windows machines, indicating a potential compatibility problem on Ubuntu. I'll investigate further to identify any compatibility issues with suitable Python version on Ubuntu.

**Comment by ditafaith** [comment]
`0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`
It seems will take time since I am not sure what the problem was during the upgrade version from 3.10 to 3.26 in my Ubuntu 20.04.
